#!/usr/bin/env python3
"""gen_configs.py — generate the full-scale characterization campaign configs.

Scans the dataset volume (default /mnt/data — the workstation's sda2, mounted
ro) and emits one odometry + one SLAM profiling config per sequence into
profiling/configs/campaign/:

  KITTI odometry color  seq 00-10   image_2/3, per-sequence calib.txt (P2/P3)
  EuRoC MAV             MH_01..05, V1_01..03, V2_01..03   (euroc source, mav0)
  TUM RGB-D fr3         long_office + the nostructure/notexture ablations
  TUM-VI 512            any dataset-*/mav0 extracted under <root>/tumvi_extracted

Paths are written with ${CUVSLAM_DATA2} (expanded by profile.py; default
/mnt/data) so the same configs run on any host that mounts the volume.

Usage:  python3 profiling/campaign/gen_configs.py [--root /mnt/data] [--out DIR]
"""
from __future__ import annotations

import argparse
import os
import struct

HERE = os.path.dirname(os.path.abspath(__file__))
DEF_OUT = os.path.join(HERE, "..", "configs", "campaign")

ODOM_FRAMES = 260          # 200 warm + steady window

KITTI_SEQS = [f"{i:02d}" for i in range(11)]
EUROC = [("MH/machine_hall", s) for s in
         ["MH_01_easy", "MH_02_easy", "MH_03_medium", "MH_04_difficult", "MH_05_difficult"]] + \
        [("VR1/vicon_room1", s) for s in ["V1_01_easy", "V1_02_medium", "V1_03_difficult"]] + \
        [("VR2/vicon_room2", s) for s in ["V2_01_easy", "V2_02_medium", "V2_03_difficult"]]
TUM_RGBD = ["rgbd_dataset_freiburg3_long_office_household",
            "rgbd_dataset_freiburg3_nostructure_notexture_far",
            "rgbd_dataset_freiburg3_nostructure_notexture_near_withloop",
            "rgbd_dataset_freiburg3_nostructure_texture_far"]
FR3 = dict(focal=[535.4, 539.2], principal=[320.1, 247.6])


def png_size(path):
    with open(path, "rb") as fh:
        d = fh.read(26)
    w, h = struct.unpack(">II", d[16:24])
    return w, h


def kitti_calib(path):
    """(f, cx, cy, baseline_m) for the color pair from calib.txt P2/P3."""
    P = {}
    for line in open(path):
        k, _, rest = line.partition(":")
        vals = rest.split()
        if len(vals) == 12:
            P[k] = [float(v) for v in vals]
    f = P["P2"][0]
    return f, P["P2"][2], P["P2"][6], (P["P2"][3] - P["P3"][3]) / f


SLAM_BLOCK = """
[slam]
enabled = true
use_gpu = true
sync_mode = true
enable_reading_internals = true
"""


def emit(out_dir, name, body_odom, body_slam):
    for suffix, body in (("odom", body_odom), ("slam", body_slam)):
        p = os.path.join(out_dir, f"{name}_{suffix}.toml")
        open(p, "w").write(body)
        yield p


def kitti_bodies(root, seq):
    calib = os.path.join(root, "dataset", "sequences", seq, "calib.txt")
    img0 = os.path.join(root, "dataset", "sequences", seq, "image_2", "000000.png")
    f, cx, cy, base = kitti_calib(calib)
    w, h = png_size(img0)
    rig = f"""
[[rig.cameras]]
size = [{w}, {h}]
focal = [{f}, {f}]
principal = [{cx}, {cy}]

[[rig.cameras]]
size = [{w}, {h}]
focal = [{f}, {f}]
principal = [{cx}, {cy}]
  [rig.cameras.rig_from_camera]
  translation = [{base:.6f}, 0.0, 0.0]
"""
    def body(frames, slam):
        return f"""# campaign: KITTI {seq} color stereo ({'SLAM' if slam else 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "image_folder"
root = "${{CUVSLAM_DATA2}}/dataset/sequences/{seq}"

  [[input.cameras]]
  images = "image_2/*.png"

  [[input.cameras]]
  images = "image_3/*.png"

  [input.timestamps]
  mode = "file"
  path = "times.txt"
  unit = "s"

[odometry]
odometry_mode = "Multicamera"
multicam_mode = "Performance"
rectified_stereo_camera = true
async_sba = false
enable_final_landmarks_export = true
{SLAM_BLOCK if slam else ''}{rig}
[output]
trajectory = "/tmp/campaign_kitti{seq}_{'slam' if slam else 'odom'}.txt"
{'pose_source = "slam"' if slam else ''}
timestamp_unit = "s"
visualize = false
print_every = 0
"""
    return body(ODOM_FRAMES, False), body(0, True)


def euroc_bodies(rel, seq):
    def body(frames, slam):
        return f"""# campaign: EuRoC {seq} stereo ({'SLAM' if slam else 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "euroc"
path = "${{CUVSLAM_DATA2}}/EuRoC/{rel}/{seq}/mav0"
use_imu = false

[odometry]
odometry_mode = "Multicamera"
rectified_stereo_camera = false
async_sba = false
enable_final_landmarks_export = true
{SLAM_BLOCK if slam else ''}
[output]
trajectory = "/tmp/campaign_{seq}_{'slam' if slam else 'odom'}.txt"
{'pose_source = "slam"' if slam else ''}
timestamp_unit = "ns"
visualize = false
print_every = 0
"""
    return body(ODOM_FRAMES, False), body(0, True)


def tum_bodies(seq):
    short = seq.replace("rgbd_dataset_freiburg3_", "fr3_")
    def body(frames, slam):
        return f"""# campaign: TUM {short} RGBD ({'SLAM' if slam else 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "tum"
path = "${{CUVSLAM_DATA2}}/TUM_RGBD/extracted/{seq}"
max_time_diff = 0.02
max_gap = 0.5

[odometry]
odometry_mode = "RGBD"
async_sba = false
enable_final_landmarks_export = true

  [odometry.rgbd]
  depth_scale_factor = 5000.0
  depth_camera_id = 0
{SLAM_BLOCK if slam else ''}
[[rig.cameras]]
size = [640, 480]
focal = {FR3['focal']}
principal = {FR3['principal']}
border_top = 20
border_bottom = 20
border_left = 10
border_right = 50

[output]
trajectory = "/tmp/campaign_{short}_{'slam' if slam else 'odom'}.txt"
{'pose_source = "slam"' if slam else ''}
timestamp_unit = "s"
visualize = false
print_every = 0
"""
    return body(ODOM_FRAMES, False), body(0, True)


def tumvi_bodies(name, path_expr):
    def body(frames, slam):
        return f"""# campaign: TUM-VI {name} fisheye stereo ({'SLAM' if slam else 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "euroc"
path = "{path_expr}"
use_imu = false

[odometry]
odometry_mode = "Multicamera"
rectified_stereo_camera = false
async_sba = false
enable_final_landmarks_export = true
{SLAM_BLOCK if slam else ''}
[output]
trajectory = "/tmp/campaign_{name}_{'slam' if slam else 'odom'}.txt"
{'pose_source = "slam"' if slam else ''}
timestamp_unit = "ns"
visualize = false
print_every = 0
"""
    return body(ODOM_FRAMES, False), body(0, True)


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default="/mnt/data")
    ap.add_argument("--tumvi-extracted", default=os.path.expanduser("~/tumvi_extracted"),
                    help="dir with extracted dataset-*_512_16/mav0 trees")
    ap.add_argument("--out", default=DEF_OUT)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    written = []

    for seq in KITTI_SEQS:
        calib = os.path.join(args.root, "dataset", "sequences", seq, "calib.txt")
        if not os.path.isfile(calib):
            print(f"[skip] KITTI {seq}: no calib.txt")
            continue
        odom, slam = kitti_bodies(args.root, seq)
        written += list(emit(args.out, f"kitti{seq}", odom, slam))

    for rel, seq in EUROC:
        if not os.path.isdir(os.path.join(args.root, "EuRoC", rel, seq, "mav0")):
            print(f"[skip] EuRoC {seq}: no mav0")
            continue
        odom, slam = euroc_bodies(rel, seq)
        written += list(emit(args.out, f"euroc_{seq}", odom, slam))

    for seq in TUM_RGBD:
        if not os.path.isdir(os.path.join(args.root, "TUM_RGBD", "extracted", seq)):
            print(f"[skip] TUM {seq}")
            continue
        odom, slam = tum_bodies(seq)
        short = seq.replace("rgbd_dataset_freiburg3_", "fr3_")
        written += list(emit(args.out, f"tum_{short}", odom, slam))

    if os.path.isdir(args.tumvi_extracted):
        for d in sorted(os.listdir(args.tumvi_extracted)):
            mav0 = os.path.join(args.tumvi_extracted, d, "mav0")
            if os.path.isdir(mav0):
                name = d.replace("dataset-", "").replace("_512_16", "")
                odom, slam = tumvi_bodies(name, mav0)
                written += list(emit(args.out, f"tumvi_{name}", odom, slam))

    print(f"[✓] {len(written)} configs in {os.path.relpath(args.out)}")


if __name__ == "__main__":
    main()
