#!/usr/bin/env python3
"""gen_configs.py — generate the full-scale characterization campaign configs.

Scans the dataset volume (default /mnt/data — the workstation's sda2, mounted
ro) and emits one odometry + one SLAM profiling config per sequence into
configs/campaign/:

  KITTI odometry color  seq 00-10   image_2/3, per-sequence calib.txt (P2/P3)
  EuRoC MAV             MH_01..05, V1_01..03, V2_01..03   (euroc source, mav0)
  TUM RGB-D fr3         long_office + the nostructure/notexture ablations
  TUM-VI 512            any dataset-*/mav0 extracted under <root>/tumvi_extracted

Paths are written with ${CUVSLAM_DATA2} (expanded by profile.py; default
/mnt/data) so the same configs run on any host that mounts the volume.

Usage:  python3 profiling/campaign/gen_configs.py [--root /mnt/data] [--out DIR]
"""
from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
# campaign configs live in the unified config tree at the repo root
DEF_OUT = os.path.join(HERE, "..", "..", "configs", "campaign")

# sequence lists + intrinsics + calibration readers live in ONE place
sys.path.insert(0, os.path.join(HERE, "..", "..", "scripts"))
from dataset_catalog import (  # noqa: E402
    EUROC, FR3, ICL, ICL_NUIM, KITTI_SEQS, TUM_RGBD, kitti_calib, png_size,
)

ODOM_FRAMES = 260          # 200 warm + steady window

# Representative subset for feature-toggle profiling (sync/async, GPU/CPU SLAM,
# EuRoC stereo/inertial/mono): profiling every toggle x all 27+ sequences would
# be an unreasonable multi-day capture. One indoor (TUM), one outdoor (KITTI),
# one MAV (EuRoC) sequence covers the three input-source families; this
# mirrors the DAMOV-style representative-sampling philosophy already used
# elsewhere in this repo (Sieve sampling, cited in PROFILING_PLAN.md).
TOGGLE_REPS = {"kitti": "00", "euroc": ("MH/machine_hall", "MH_01_easy"),
               "tum": "rgbd_dataset_freiburg3_long_office_household"}
EUROC_VARIANT_REPS = [("MH/machine_hall", "MH_01_easy"), ("VR1/vicon_room1", "V1_01_easy")]


def slam_block(kind):
    """kind: None=odom(no block), 'slam'=sync+GPU (default), 'slam_async',
    'slam_cpu'. Mirrors gen_accuracy_configs.py's slam_block for consistency."""
    if kind is None:
        return ""
    sync = "false" if kind == "slam_async" else "true"
    gpu = "false" if kind == "slam_cpu" else "true"
    return f"""
[slam]
enabled = true
use_gpu = {gpu}
sync_mode = {sync}
enable_reading_internals = true
"""


SLAM_BLOCK = slam_block("slam")   # kept for any external references


def emit(out_dir, name, bodies):
    """bodies: dict of suffix -> config text (e.g. {'odom':..., 'slam':...,
    'slam_async':..., 'slam_cpu':...}). Always writes '_odom' + at least
    '_slam' so run_campaign.sh's *_odom.toml/_slam.toml pairing keeps working;
    extra suffixes (slam_async, slam_cpu) are additional capture targets."""
    for suffix, body in bodies.items():
        p = os.path.join(out_dir, f"{name}_{suffix}.toml")
        open(p, "w").write(body)
        yield p


def kitti_bodies(root, seq, extra_kinds=None):
    calib = os.path.join(root, "dataset", "sequences", seq, "calib.txt")
    img0 = os.path.join(root, "dataset", "sequences", seq, "image_2", "000000.png")
    f, cx, cy, base = kitti_calib(calib)
    w, h = png_size(img0)
    rig = f"""
[[rig.cameras]]
size = [{w}, {h}]
focal = [{f}, {f}]
principal = [{cx}, {cy}]

[[rig.cameras]]
size = [{w}, {h}]
focal = [{f}, {f}]
principal = [{cx}, {cy}]
  [rig.cameras.rig_from_camera]
  translation = [{base:.6f}, 0.0, 0.0]
"""
    def body(frames, kind):
        return f"""# campaign: KITTI {seq} color stereo ({kind or 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "image_folder"
root = "${{CUVSLAM_DATA2}}/dataset/sequences/{seq}"

  [[input.cameras]]
  images = "image_2/*.png"

  [[input.cameras]]
  images = "image_3/*.png"

  [input.timestamps]
  mode = "file"
  path = "times.txt"
  unit = "s"

[odometry]
odometry_mode = "Multicamera"
multicam_mode = "Performance"
rectified_stereo_camera = true
async_sba = false
enable_final_landmarks_export = true
{slam_block(kind)}{rig}
[output]
trajectory = "/tmp/campaign_kitti{seq}_{kind or 'odom'}.txt"
{'pose_source = "slam"' if kind else ''}
timestamp_unit = "s"
visualize = false
print_every = 0
"""
    d = {"odom": body(ODOM_FRAMES, None), "slam": body(0, "slam")}
    for k in (extra_kinds or []):
        d[k] = body(0, k)
    return d


def euroc_bodies(rel, seq, extra_kinds=None, variant="stereo"):
    """variant: 'stereo' (default, Multicamera), 'inertial' (IMU + Inertial
    mode — memory profile of the IMU-fusion path), 'mono' (single camera).
    Suffix carries the variant so stereo (the default family name) stays
    backward-compatible: euroc_<seq>_odom.toml == stereo variant unsuffixed;
    euroc_<seq>_inertial_odom.toml / euroc_<seq>_mono_odom.toml for the others."""
    mode = {"stereo": "Multicamera", "inertial": "Inertial", "mono": "Mono"}[variant]
    use_imu = "true" if variant == "inertial" else "false"

    def body(frames, kind):
        return f"""# campaign: EuRoC {seq} {variant} ({kind or 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "euroc"
path = "${{CUVSLAM_DATA2}}/EuRoC/{rel}/{seq}/mav0"
use_imu = {use_imu}

[odometry]
odometry_mode = "{mode}"
rectified_stereo_camera = false
async_sba = false
enable_final_landmarks_export = true
{slam_block(kind)}
[output]
trajectory = "/tmp/campaign_{seq}_{variant}_{kind or 'odom'}.txt"
{'pose_source = "slam"' if kind else ''}
timestamp_unit = "ns"
visualize = false
print_every = 0
"""
    d = {"odom": body(ODOM_FRAMES, None), "slam": body(0, "slam")}
    for k in (extra_kinds or []):
        d[k] = body(0, k)
    return d


def tum_bodies(seq, extra_kinds=None):
    short = seq.replace("rgbd_dataset_freiburg3_", "fr3_")
    def body(frames, kind):
        return f"""# campaign: TUM {short} RGBD ({kind or 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "tum"
path = "${{CUVSLAM_DATA2}}/TUM_RGBD/extracted/{seq}"
max_time_diff = 0.02
max_gap = 0.5

[odometry]
odometry_mode = "RGBD"
async_sba = false
enable_final_landmarks_export = true

  [odometry.rgbd]
  depth_scale_factor = 5000.0
  depth_camera_id = 0
{slam_block(kind)}
[[rig.cameras]]
size = [640, 480]
focal = {FR3['focal']}
principal = {FR3['principal']}
border_top = 20
border_bottom = 20
border_left = 10
border_right = 50

[output]
trajectory = "/tmp/campaign_{short}_{kind or 'odom'}.txt"
{'pose_source = "slam"' if kind else ''}
timestamp_unit = "s"
visualize = false
print_every = 0
"""
    d = {"odom": body(ODOM_FRAMES, None), "slam": body(0, "slam")}
    for k in (extra_kinds or []):
        d[k] = body(0, k)
    return d


def icl_bodies(seq, extra_kinds=None):
    """ICL-NUIM (Mono-Depth, synthetic RGB-D) — added 2026-07-07. Reuses the
    tum source (same associations->rgb.txt/depth.txt index as the accuracy
    matrix generator). ICL timestamps are frame indices (dt=1.0), so
    max_gap/max_time_diff are widened vs the real-camera TUM configs — this
    is the same fix applied in gen_accuracy_configs.py's icl_cfg."""
    short = seq.replace("_frei_png", "")
    def body(frames, kind):
        return f"""# campaign: ICL-NUIM {short} RGBD ({kind or 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "tum"
path = "${{CUVSLAM_DATA2}}/ICL-NUIM/{seq}"
max_time_diff = 0.5
max_gap = 2.0

[odometry]
odometry_mode = "RGBD"
async_sba = false
enable_final_landmarks_export = true

  [odometry.rgbd]
  depth_scale_factor = 5000.0
  depth_camera_id = 0
{slam_block(kind)}
[[rig.cameras]]
size = [640, 480]
focal = {ICL['focal']}
principal = {ICL['principal']}

[output]
trajectory = "/tmp/campaign_icl_{short}_{kind or 'odom'}.txt"
{'pose_source = "slam"' if kind else ''}
timestamp_unit = "s"
visualize = false
print_every = 0
"""
    d = {"odom": body(ODOM_FRAMES, None), "slam": body(0, "slam")}
    for k in (extra_kinds or []):
        d[k] = body(0, k)
    return d


def tumvi_bodies(name, path_expr, extra_kinds=None):
    def body(frames, kind):
        return f"""# campaign: TUM-VI {name} fisheye stereo ({kind or 'odometry'}) — generated by gen_configs.py
[run]
verbosity = 0
start_index = 0
max_frames = {frames}

[input]
type = "euroc"
path = "{path_expr}"
use_imu = false

[odometry]
odometry_mode = "Multicamera"
rectified_stereo_camera = false
async_sba = false
enable_final_landmarks_export = true
{slam_block(kind)}
[output]
trajectory = "/tmp/campaign_{name}_{kind or 'odom'}.txt"
{'pose_source = "slam"' if kind else ''}
timestamp_unit = "ns"
visualize = false
print_every = 0
"""
    d = {"odom": body(ODOM_FRAMES, None), "slam": body(0, "slam")}
    for k in (extra_kinds or []):
        d[k] = body(0, k)
    return d


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--root", default="/mnt/data")
    ap.add_argument("--tumvi-extracted", default=os.path.expanduser("~/tumvi_extracted"),
                    help="dir with extracted dataset-*_512_16/mav0 trees")
    ap.add_argument("--out", default=DEF_OUT)
    args = ap.parse_args()
    os.makedirs(args.out, exist_ok=True)
    written = []

    # toggle extras (slam_async + slam_cpu) go on ONE representative per
    # input-source family (TOGGLE_REPS); everything else emits odom+slam.
    TOGGLES = ["slam_async", "slam_cpu"]

    for seq in KITTI_SEQS:
        calib = os.path.join(args.root, "dataset", "sequences", seq, "calib.txt")
        if not os.path.isfile(calib):
            print(f"[skip] KITTI {seq}: no calib.txt")
            continue
        extra = TOGGLES if seq == TOGGLE_REPS["kitti"] else None
        written += list(emit(args.out, f"kitti{seq}", kitti_bodies(args.root, seq, extra)))

    for rel, seq in EUROC:
        if not os.path.isdir(os.path.join(args.root, "EuRoC", rel, seq, "mav0")):
            print(f"[skip] EuRoC {seq}: no mav0")
            continue
        extra = TOGGLES if (rel, seq) == TOGGLE_REPS["euroc"] else None
        written += list(emit(args.out, f"euroc_{seq}", euroc_bodies(rel, seq, extra)))
        # sensor-variant reps: also profile the inertial (IMU-fusion) and mono paths
        if (rel, seq) in EUROC_VARIANT_REPS:
            for variant in ("inertial", "mono"):
                written += list(emit(args.out, f"euroc_{seq}_{variant}",
                                     euroc_bodies(rel, seq, variant=variant)))

    for seq in TUM_RGBD:
        if not os.path.isdir(os.path.join(args.root, "TUM_RGBD", "extracted", seq)):
            print(f"[skip] TUM {seq}")
            continue
        extra = TOGGLES if seq == TOGGLE_REPS["tum"] else None
        short = seq.replace("rgbd_dataset_freiburg3_", "fr3_")
        written += list(emit(args.out, f"tum_{short}", tum_bodies(seq, extra)))

    for seq in ICL_NUIM:
        if not os.path.isdir(os.path.join(args.root, "ICL-NUIM", seq)):
            print(f"[skip] ICL {seq}")
            continue
        short = seq.replace("_frei_png", "")
        written += list(emit(args.out, f"icl_{short}", icl_bodies(seq)))

    if os.path.isdir(args.tumvi_extracted):
        for d in sorted(os.listdir(args.tumvi_extracted)):
            mav0 = os.path.join(args.tumvi_extracted, d, "mav0")
            # the euroc source needs EuRoC-style cam0/sensor.yaml; raw TUM-VI
            # tars ship a different calib layout, so skip those (corridor1 was
            # pre-converted). TODO: TUM-VI->EuRoC calib conversion.
            if os.path.isdir(mav0) and os.path.isfile(os.path.join(mav0, "cam0", "sensor.yaml")):
                name = d.replace("dataset-", "").replace("_512_16", "")
                written += list(emit(args.out, f"tumvi_{name}", tumvi_bodies(name, mav0)))
            elif os.path.isdir(mav0):
                print(f"[skip] TUM-VI {d}: no cam0/sensor.yaml (needs calib conversion)")

    print(f"[✓] {len(written)} configs in {os.path.relpath(args.out)}")


if __name__ == "__main__":
    main()
